package:
    name: nrel-wtk
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - filelock
    - netCDF4
    - NREL-rex>=0.2.44
  run:
    - python
    - pip
    - filelock
    - netCDF4
    - NREL-rex>=0.2.44

about:
  home: "https://github.com/NREL/wtk"
  license: BSD 3-Clause
  summary: "WIND Toolkit and wind resource post-processing tools"
  doc_url: "https://nrel.github.io/wtk"
  dev_url: "https://github.com/NREL/wtk"
