package:
    name: nrel-farms
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy>=1.16
    - pandas
  run:
    - python
    - pip
    - {{ pin_compatible('numpy') }}
    - pandas

about:
  home: "https://github.com/NREL/farms"
  license: BSD 3-Clause
  summary: "The Fast All-sky Radiation Model for Solar applications (FARMS) is used to compute cloudy irradiance."
  doc_url: "https://nrel.github.io/farms"
  dev_url: "https://github.com/NREL/farms"
